import React, { useRef, useState } from 'react';
import { Archive, ArchiveRestore, Bell, Download, FileText, History, Pencil, RefreshCw, Share2, Upload, X } from 'lucide-react';
import { ACCESS_META, CompanyDocument, DOCUMENT_CATEGORIES, DocumentAccessLevel, DocumentCategory } from '../../data/supplierTypes';
import { daysUntil, documentExpiry } from '../../data/supplierStore';
import { renameDocument, replaceDocument, revokeShare, setDocumentArchived, shareDocument, updateDocumentSettings, uploadDocument } from '../../data/supplierService';
import { ProfileDialog } from '../ProfileDialog';
import { StatusPill, btnPrimary, btnSecondary, inputCls, labelCls } from '../NetworkShared';
import { DemoNote, fmtDate } from '../marketHub/MarketHubShared';
import { SW, fmtMb } from './SupplierShared';
import { TextField } from './ProfileEditors';

const sizeOf = (f: File) => Math.max(0.1, Math.round((f.size / 1048576) * 10) / 10);

export const ExpiryPill: React.FC<{ doc: CompanyDocument }> = ({ doc }) => {
  const s = documentExpiry(doc);
  const n = daysUntil(doc.expiry);
  if (s === 'none') return <span className="text-xs text-slate-400">No expiry</span>;
  if (s === 'expired') return <span className="inline-flex px-2 py-0.5 rounded-md bg-rose-50 border border-rose-200 text-[11px] font-semibold text-rose-700">Expired {fmtDate(doc.expiry)}</span>;
  if (s === 'reminder') return <StatusPill tone="amber">Expires in {n} days</StatusPill>;
  return <span className="text-xs text-slate-600">Expires {fmtDate(doc.expiry)}</span>;
};

export const downloadPlaceholder = (doc: CompanyDocument, company: string) => {
  const blob = new Blob([`SOKO demo document\n\nCompany: ${company}\nDocument: ${doc.name}\nFile: ${doc.fileName}\nVersion: ${doc.versions.length}\n\nThis is a placeholder file generated by the prototype.`], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${doc.name}.txt`;
  a.click();
  window.setTimeout(() => URL.revokeObjectURL(url), 1000);
};

export const UploadDocumentDialog: React.FC<{ sw: SW; available: number; defaultCategory?: DocumentCategory; onClose: () => void }> = ({ sw, available, defaultCategory, onClose }) => {
  const fileRef = useRef<HTMLInputElement>(null);
  const [file, setFile] = useState<{ name: string; sizeMb: number } | null>(null);
  const [name, setName] = useState('');
  const [category, setCategory] = useState<DocumentCategory>(defaultCategory ?? 'Other Company Documents');
  const [expiry, setExpiry] = useState('');
  const [reminderDays, setReminderDays] = useState(30);
  const [access, setAccess] = useState<DocumentAccessLevel>('team');

  const submit = () => {
    if (!file) return sw.notify('Choose a file to upload.');
    if (sw.run(uploadDocument(sw.ctx, { name: name || file.name.replace(/\.[^.]+$/, ''), category, fileName: file.name, sizeMb: file.sizeMb, expiry, reminderDays, access }), 'Document uploaded')) onClose();
  };

  return (
    <ProfileDialog
      title="Upload document"
      subtitle={`${fmtMb(available)} available. Documents are private to your company until you share them.`}
      onClose={onClose}
      footer={
        <div className="flex justify-end gap-2">
          <button type="button" onClick={onClose} className={btnSecondary}>Cancel</button>
          <button type="button" onClick={submit} disabled={!file} className={btnPrimary}>Upload</button>
        </div>
      }
    >
      <div className="space-y-3">
        <button type="button" onClick={() => fileRef.current?.click()} className="w-full rounded-xl border-2 border-dashed border-slate-300 px-4 py-6 text-center hover:border-blue-400 hover:bg-blue-50/40 transition-colors cursor-pointer">
          {file ? (
            <span className="text-sm font-semibold text-slate-900">{file.name} · {file.sizeMb} MB</span>
          ) : (
            <>
              <Upload className="w-5 h-5 mx-auto text-slate-400" />
              <span className="mt-1 block text-sm font-semibold text-slate-800">Choose a file</span>
            </>
          )}
        </button>
        <input
          ref={fileRef}
          type="file"
          className="hidden"
          onChange={(e) => {
            const f = e.target.files?.[0];
            if (f) {
              setFile({ name: f.name, sizeMb: sizeOf(f) });
              if (!name) setName(f.name.replace(/\.[^.]+$/, ''));
            }
          }}
        />
        <TextField label="Document name" value={name} onChange={setName} />
        <label className="block">
          <span className={labelCls}>Category</span>
          <select value={category} onChange={(e) => setCategory(e.target.value as DocumentCategory)} className={inputCls}>
            {DOCUMENT_CATEGORIES.map((c) => <option key={c}>{c}</option>)}
          </select>
        </label>
        <div className="grid grid-cols-2 gap-3">
          <TextField label="Expiry date (optional)" type="date" value={expiry} onChange={setExpiry} />
          <label className="block">
            <span className={labelCls}>Reminder</span>
            <select value={reminderDays} onChange={(e) => setReminderDays(Number(e.target.value))} className={inputCls}>
              {[14, 30, 60, 90].map((d) => <option key={d} value={d}>{d} days before expiry</option>)}
            </select>
          </label>
        </div>
        <label className="block">
          <span className={labelCls}>Who in your team can open it</span>
          <select value={access} onChange={(e) => setAccess(e.target.value as DocumentAccessLevel)} className={inputCls}>
            {(Object.keys(ACCESS_META) as DocumentAccessLevel[]).map((a) => <option key={a} value={a}>{ACCESS_META[a].label}</option>)}
          </select>
        </label>
        <DemoNote>Uploads are simulated: only the file name and size are recorded in this prototype.</DemoNote>
      </div>
    </ProfileDialog>
  );
};

type Mode = 'details' | 'rename' | 'settings' | 'share';

export const DocumentDetailDialog: React.FC<{ sw: SW; doc: CompanyDocument; onClose: () => void }> = ({ sw, doc, onClose }) => {
  const [mode, setMode] = useState<Mode>('details');
  const [name, setName] = useState(doc.name);
  const [settings, setSettings] = useState({ expiry: doc.expiry ?? '', reminderDays: doc.reminderDays, access: doc.access, category: doc.category });
  const [shareTo, setShareTo] = useState('');
  const [days, setDays] = useState(30);
  const replaceRef = useRef<HTMLInputElement>(null);
  const manage = sw.can('documents.manage');
  const share = sw.can('documents.share');

  return (
    <ProfileDialog title={doc.name} subtitle={`${doc.category} · ${fmtMb(doc.sizeMb)} · version ${doc.versions.length}`} size="lg" onClose={onClose}>
      <div className="grid md:grid-cols-[200px_1fr] gap-5">
        <div className="rounded-xl border border-slate-200 bg-slate-50 aspect-[3/4] flex flex-col items-center justify-center text-center p-4">
          <FileText className="w-10 h-10 text-slate-400" />
          <p className="mt-2 text-xs font-semibold text-slate-700 break-all">{doc.fileName}</p>
          <p className="mt-1 text-[11px] text-slate-500">Preview placeholder</p>
        </div>
        <div className="space-y-4 min-w-0">
          {mode === 'details' && (
            <>
              <dl className="grid grid-cols-2 gap-3 text-sm">
                <div><dt className="text-xs text-slate-500">Uploaded</dt><dd className="font-medium text-slate-900">{fmtDate(doc.uploadedAt)} · {doc.uploadedBy}</dd></div>
                <div><dt className="text-xs text-slate-500">Expiry</dt><dd><ExpiryPill doc={doc} /></dd></div>
                <div><dt className="text-xs text-slate-500">Team access</dt><dd className="font-medium text-slate-900">{ACCESS_META[doc.access].label}</dd></div>
                <div>
                  <dt className="text-xs text-slate-500">Reminder</dt>
                  <dd className="font-medium text-slate-900 flex items-center gap-1"><Bell className="w-3.5 h-3.5 text-slate-400" />{doc.expiry ? `${doc.reminderDays} days before expiry` : '—'}</dd>
                </div>
              </dl>
              <div className="flex flex-wrap gap-2">
                <button type="button" onClick={() => { downloadPlaceholder(doc, sw.company.profile.tradingName); sw.notify('Download started (placeholder file)'); }} className={btnSecondary}><Download className="w-4 h-4" /> Download</button>
                {share && !doc.archived && <button type="button" onClick={() => setMode('share')} className={btnSecondary}><Share2 className="w-4 h-4" /> Share</button>}
                {manage && <button type="button" onClick={() => setMode('rename')} className={btnSecondary}><Pencil className="w-4 h-4" /> Rename</button>}
                {manage && <button type="button" onClick={() => replaceRef.current?.click()} className={btnSecondary}><RefreshCw className="w-4 h-4" /> Replace</button>}
                {manage && <button type="button" onClick={() => setMode('settings')} className={btnSecondary}><Bell className="w-4 h-4" /> Expiry & access</button>}
                {manage && (
                  <button type="button" onClick={() => sw.run(setDocumentArchived(sw.ctx, doc.id, !doc.archived), doc.archived ? 'Document restored' : 'Document archived') && onClose()} className={btnSecondary}>
                    {doc.archived ? <ArchiveRestore className="w-4 h-4" /> : <Archive className="w-4 h-4" />} {doc.archived ? 'Restore' : 'Archive'}
                  </button>
                )}
                <input
                  ref={replaceRef}
                  type="file"
                  className="hidden"
                  onChange={(e) => {
                    const f = e.target.files?.[0];
                    if (f) sw.run(replaceDocument(sw.ctx, doc.id, f.name, sizeOf(f)), 'New version uploaded');
                    e.target.value = '';
                  }}
                />
              </div>

              <div>
                <p className="text-[11px] font-semibold uppercase tracking-wide text-slate-500 flex items-center gap-1.5"><Share2 className="w-3.5 h-3.5" /> Controlled sharing</p>
                {doc.shares.length === 0 ? (
                  <p className="mt-1 text-sm text-slate-500">Not shared. Only your team can see this document.</p>
                ) : (
                  <ul className="mt-2 space-y-1.5">
                    {doc.shares.map((s) => (
                      <li key={s.id} className="flex items-center gap-2 text-sm">
                        <span className="flex-1 min-w-0 truncate"><strong className="font-semibold">{s.company}</strong> · until {fmtDate(s.until)} · by {s.by}</span>
                        {share && (
                          <button type="button" onClick={() => sw.run(revokeShare(sw.ctx, doc.id, s.id), 'Access revoked')} className="inline-flex items-center gap-1 text-xs font-semibold text-rose-700 hover:underline cursor-pointer">
                            <X className="w-3.5 h-3.5" /> Revoke
                          </button>
                        )}
                      </li>
                    ))}
                  </ul>
                )}
              </div>

              <div>
                <p className="text-[11px] font-semibold uppercase tracking-wide text-slate-500 flex items-center gap-1.5"><History className="w-3.5 h-3.5" /> Version history</p>
                <ol className="mt-2 space-y-1">
                  {[...doc.versions].reverse().map((v) => (
                    <li key={v.version} className="text-sm text-slate-700">
                      v{v.version} · {v.fileName} <span className="text-slate-500">· {fmtDate(v.at)} · {v.by}</span>
                    </li>
                  ))}
                </ol>
              </div>
            </>
          )}

          {mode === 'rename' && (
            <div className="space-y-3">
              <TextField label="Document name" value={name} onChange={setName} />
              <div className="flex gap-2">
                <button type="button" onClick={() => setMode('details')} className={btnSecondary}>Back</button>
                <button type="button" onClick={() => sw.run(renameDocument(sw.ctx, doc.id, name), 'Document renamed') && setMode('details')} className={btnPrimary}>Save name</button>
              </div>
            </div>
          )}

          {mode === 'settings' && (
            <div className="space-y-3">
              <label className="block">
                <span className={labelCls}>Category</span>
                <select value={settings.category} onChange={(e) => setSettings({ ...settings, category: e.target.value as DocumentCategory })} className={inputCls}>
                  {DOCUMENT_CATEGORIES.map((c) => <option key={c}>{c}</option>)}
                </select>
              </label>
              <div className="grid grid-cols-2 gap-3">
                <TextField label="Expiry date" type="date" value={settings.expiry} onChange={(expiry) => setSettings({ ...settings, expiry })} />
                <label className="block">
                  <span className={labelCls}>Reminder</span>
                  <select value={settings.reminderDays} onChange={(e) => setSettings({ ...settings, reminderDays: Number(e.target.value) })} className={inputCls}>
                    {[14, 30, 60, 90].map((d) => <option key={d} value={d}>{d} days before</option>)}
                  </select>
                </label>
              </div>
              <label className="block">
                <span className={labelCls}>Team access</span>
                <select value={settings.access} onChange={(e) => setSettings({ ...settings, access: e.target.value as DocumentAccessLevel })} className={inputCls}>
                  {(Object.keys(ACCESS_META) as DocumentAccessLevel[]).map((a) => <option key={a} value={a}>{ACCESS_META[a].label}</option>)}
                </select>
              </label>
              <div className="flex gap-2">
                <button type="button" onClick={() => setMode('details')} className={btnSecondary}>Back</button>
                <button type="button" onClick={() => sw.run(updateDocumentSettings(sw.ctx, doc.id, settings), 'Document settings saved') && setMode('details')} className={btnPrimary}>Save</button>
              </div>
            </div>
          )}

          {mode === 'share' && (
            <div className="space-y-3">
              <p className="text-sm text-slate-600">Give a specific company time-limited access to this one document. Nothing else in your Document Center is shared.</p>
              <TextField label="Share with company" value={shareTo} onChange={setShareTo} placeholder="e.g. Al Habtoor Contracting" />
              <label className="block">
                <span className={labelCls}>Access period</span>
                <select value={days} onChange={(e) => setDays(Number(e.target.value))} className={inputCls}>
                  {[7, 14, 30, 90].map((d) => <option key={d} value={d}>{d} days</option>)}
                </select>
              </label>
              <div className="flex gap-2">
                <button type="button" onClick={() => setMode('details')} className={btnSecondary}>Back</button>
                <button type="button" onClick={() => sw.run(shareDocument(sw.ctx, doc.id, shareTo, days), `Shared with ${shareTo.trim()} (simulated)`) && setMode('details')} className={btnPrimary}>Share document</button>
              </div>
            </div>
          )}
        </div>
      </div>
    </ProfileDialog>
  );
};
